version: "3.7"
services:
  app:
    build:
      args:
        user: npoHris
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hris-backend
    container_name: hris-backend-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - hris-backend

  db:
    image: mysql:5.7
    container_name: hris-backend-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_HRIS}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - hris-backend

  hris-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hris-phpmyadmin
    restart: unless-stopped
    networks:
      - hris-backend
    depends_on:
      - db
    ports:
      - "8003:80"
    environment:
      PMA_HOST: db

  nginx:
    image: nginx:alpine
    container_name: hris-backend-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - hris-backend

networks:
  hris-backend:
    driver: bridge
