<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    </head>
    <style>

      table {
        width: 100%;
        margin-top : 20px;
        border-collapse: collapse;
      }
      .label1 {
        color: #383838;
        text-transform: uppercase;
        font-size: 20px;
        font-weight : 600;
      }

     @font-face {
        font-family: 'Helvetica';
        font-weight: normal;
        font-style: normal;
        font-variant: normal;
        src: url("https://fonts.googleapis.com/css?family=Baloo+Chettan+2&display=swap");
      }
      body {
        font-family: Helvetica, sans-serif;
      }
      .flex-center {
          align-items: center;
          display: flex;
          justify-content: center;
          text-align: center;
      }
      .position-ref {
        position: relative;
      }
      .image-header {
        width : 40px;
        height : 40px;
        margin-right : 350px;
      }
      .title {
        text-align: center;
        font-size: 18px;
        font-weight : 700;
        color: #383838;
        position : absolute;
        top : 30;
        left : 120;
      }
      .title2 {
        text-align: center;
        font-size: 16px;
        font-weight : 500;
        color: #383838;
        text-align : center;
        margin-top : 10px;
      }
      .divider {
        margin-top : 10px;
        width : 100%;
        border-bottom : 1px solid #383838;
      }
      .divider2 {
        position : absolute;
        width : 100%;
        top : 80;
        border-bottom : 1px solid gray;
      }
      .span-label {
        font-size: 13px;
        color: #525252;
      }
      .span-value {
        font-size: 13px;
        color: #1f1f1f;
      }
      .header-row {
        border-bottom : 3px solid gray;
        margin-bottom : 10px;
      }

      th {
        font-size: 12px;
        text-transform: uppercase;
        text-align : left;
        color: gray;
        height: 20px;
        border-bottom : 3px solid gray;
        padding-bottom: 8px;
      }
      td{
        width: 12%;
        font-size: 10px;
        color: #525252;
        height: 40px;
        border-bottom : 0.5px solid gray;
      }

      .div-employee-data {
        margin-top : 15px;
        /* flexbox not worling dompdf */
      }

      .col-1 {
        margin-right : 160px;
        /* flexbox not worling dompdf */
      }

    </style>

    <body>
        @foreach($data as $key => $employee)
            @php
                end($data);
                $is_last = false;
                if ($key === key($data))
                    $is_last = true;
            @endphp
            @if ($is_last)
                <div>
            @else
                <div style="page-break-after:always;">
            @endif

                <div class="flex-center position-ref">
                    <img src="{{ $logo }}" class="image-header">
                    <div class="label1 ">National Printing Office</div>
                </div>
                <div class="title">
                    Summary of Lates, Absences and Undertimes
                </div>
                <div class="title2">
                    Report Period : {{$employee['monthData'][0]['month']}} -
                    {{$employee['monthData'][count($employee['monthData'])-1]['month']}}
                    {{$employee['monthData'][0]['year']}}
                    <!-- date here -->
                </div>
                <div class="divider"> </div>
                <div class="divider2"> </div>
                <div class="div-employee-data">
                    <table style="width: 100%; border-collapse: collapse; margin-top: 0px;">
                        <tr>
                            <td style="border-bottom: none; line-height: 22px; width: 65%">
                                <span class="span-label">Employee Name : </span><span class="span-value">{{$employee['name']}}</span> <br />
                                <span class="span-label">Division : </span><span class="span-value">{{$employee['division']}}</span>
                            </td>
                            <td style="border-bottom: none; line-height: 22px; width: 35%">
                                <span class="span-label">Generated by : </span><span class="span-value">{{$generatedBy}}</span> <br />
                                <span class="span-label">Date Generated : </span><span class="span-value">{{date('M. d, Y')}}</span>
                            </td>
                        </tr>
                    </table>
                </div>
                <table>
                    <tr>
                        <th style="width: 20%;">Months</td>
                        <th style="width: 10%;text-align : center;">Absence</td>
                        <th style="width: 10%;text-align : center;">Lates</td>
                        <th style="width: 10%;text-align : center;">Undertime</td>
                    </tr>
                    @foreach ($employee['monthData'] as $item)
                        <tr>
                            <td>{{$item['month']}}</td>
                            <td style="width: 10%;text-align : center;" >{{$item['absences']}}</td>
                            <td style="width: 10%;text-align : center;" >{{$item['lates']}}</td>
                            <td style="width: 10%;text-align : center;" >{{$item['undertimes']}}</td>
                        </tr>
                    @endforeach
                </table>
            </div>
        @endforeach
    </body>
</html>
